// <auto-generated />
namespace LibraryManagementUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddingBorrowHistories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingBorrowHistories));
        
        string IMigrationMetadata.Id
        {
            get { return "202007170123538_AddingBorrowHistories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
